# The key value pairs found below are available within the templates.


jq_version: 1.2
root: '/jq'
footer: |
  
  This website is made with [Bonsai](http://www.tinytree.info) and
  [Twitter Bootstrap](http://twitter.github.com/bootstrap/), themed
  with [Bootswatch](http://bootswatch.com).

  jq is licensed under the MIT license (code) and the
  [CC-BY-3.0](http://creativecommons.org/licenses/by/3.0/) license
  (docs).